# fuck yeah its bash
# you got a problem with that?

CUR="core/auto/load_gl.h"
DEF="core/auto/load_gl."

echo "

// AUTOGENERATED FILE

#ifndef FUR_GL_LOADER_H
#define FUR_GL_LOADER_H

#include <core/macros.h>

#include <GL/gl.h>

#ifdef __cplusplus
extern \"C\" {
#endif

#ifdef _WIN32
#include <windows.h>
#define APIENTRYP APIENTRY *
#include <GL/glext.h>
#endif

#define FUNC(name, ret_type, ...)                       \\
    typedef ret_type (APIENTRYP name##_t)(__VA_ARGS__); \\
    extern name##_t name

extern b8 fur_use_wayland;

void fur_gl_load(void);  

#ifdef _WIN32
FUNC(glActiveTexture, void, GLenum texture);
#endif

" > "$CUR"

sed -E 's/^(.*\S.*)$/FUNC(\1);/' "$DEF" >> "$CUR"

echo "

#ifdef __cplusplus
}
#endif

#endif" >> "$CUR"


CUR="core/auto/load_gl.c"

echo "

// AUTOGENERATED FILE

#include <stdio.h>
#include \"load_gl.h\"

#include <core/macros.h>

#ifdef _WIN32
    #include <windows.h>

    #define LOAD(name)                                                              \\
                do {                                                                \\
                    name = (name##_t)wglGetProcAddress(#name);                      \\
                    if (!name) { printf(\"failed to load %s!\n\", #name); return; } \\
                } while (0)
#else
    #include <EGL/egl.h>
    #include <GL/glx.h>

    #define LOAD(name)                                                              \\
                do {                                                                \\
                    if (fur_use_wayland) name = (name##_t)eglGetProcAddress(#name); \\
                    else name = (name##_t)glXGetProcAddress((const GLubyte*)name);  \\
                    if (!name) { printf(\"failed to load %s!\n\", #name); return; } \\
                } while(0)
#endif

#define FUNC_C(name, ret_type, ...) \\
    name##_t name = NULL

b8 fur_use_wayland;

#ifdef _WIN32
FUNC_C(glActiveTexture, void, GLenum texture);
#endif

" > "$CUR"

sed -E 's/^(.*\S.*)$/FUNC_C(\1);/' "$DEF" >> "$CUR"

echo "
void fur_gl_load(void) {

#ifdef _WIN32
LOAD(glActiveTexture);
#endif

" >> "$CUR"

sed -E 's/^([^,]+),.*$/LOAD(\1);/' "$DEF" >> "$CUR"

echo "}" >> "$CUR"

