#ifndef FUR_PLATFORM_GLFW_INPUT_H
#define FUR_PLATFORM_GLFW_INPUT_H

typedef struct { int a; } pretendTsIsSomethingBecauseINeedToHaveTheWindowBuildAndToDoThatINeedToHaveHeaderFilesThatAreIncludedInCFilesHaveSomeShitInThemSoYeah; 

#endif
